### PR TITLE
New release with manual curations

### PR DESCRIPTION
**Pull request by hkir-dev**
Fixes Issues:
- #16 
- #17 
- #18 

`uberon-bridge-to-hba.obo` extension changed to [uberon-bridge-to-hba.owl](https://github.com/obophenotype/uberon/blob/master/src/ontology/bridge/uberon-bridge-to-hba.owl) in `Uberon`.

WARNING: Please note that `CL:4023073 (obsolete choroid plexus cell)` is deprecated now and in the [taxonomy_details.yaml](https://github.com/hkir-dev/whole_human_brain_ontology/blob/issue_18/src/dendrograms/taxonomy_details.yaml#L172) config we still use it.
https://github.com/obophenotype/cell-ontology/issues/2043

### CODE REVIEW

**Comment by dosumis** [comment]
> WARNING: Please note that CL:4023073 (obsolete choroid plexus cell) is deprecated now and in the [taxonomy_details.yaml](https://github.com/hkir-dev/whole_human_brain_ontology/blob/issue_18/src/dendrograms/taxonomy_details.yaml#L172) config we still use it.
https://github.com/obophenotype/cell-ontology/issues/2043

Update to
CL:0000706 | choroid plexus epithelial cell

Already updated in spreadsheets for CAS

**Comment by dosumis** [comment]
Looks good.  I need to update the the config (I'll let you know when I'm done).  Also noticed that we need to update "native cell" in the design pattern to "cell" as native cell has been obsoleted.

**Review by dosumis — APPROVED** [review]
OWL looks good.  I updated config and pattern (switched 'native cell' --> 'cell').  Probably want to try another build to test my changes before merging.

**Comment by hkir-dev** [comment]
Fix for the issue #20 added and ontology rebuild.

**Comment by dosumis** [comment]
Build looks like it still has classes for root classes where the YAML config indicates they should not.

image

image

**Comment by hkir-dev** [comment]
We are still creating them because seems we have an additional legacy condition: `create a class for the root node if root node is a leaf note as well` 

I am removing this assumption since we have better control with `Create_class` configuration now.

**Comment by hkir-dev** [comment]
Ontology rebuild completed

**Pull request merged**
